name = "GeoStatsBase"
uuid = "323cb8eb-fbf6-51c0-afd0-f8fba70507b2"
author = "JÃºlio Hoffimann <julio.hoffimann@gmail.com>"
version = "0.17.0"

[deps]
AverageShiftedHistograms = "77b51b56-6f8f-5c3a-9cb4-d71f9594ea6e"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DensityRatioEstimation = "ab46fb84-d57c-11e9-2f65-6f72e4a7229f"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LossFunctions = "30fc2ffe-d236-52d8-8643-a9d8f7c094a7"
MLJModelInterface = "e80e1ace-859a-464e-9ed9-23947d8ae3ea"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
ReferenceFrameRotations = "74f56ac7-18b3-5285-802d-d4bd4f104033"
ScientificTypes = "321657f4-b219-11e9-178b-2701a2544e81"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
Transducers = "28d57a85-8fef-5791-bfe6-a80928e7c999"

[compat]
AverageShiftedHistograms = "0.8"
CSV = "0.5, 0.6, 0.7, 0.8"
CategoricalArrays = "0.7, 0.8, 0.9"
Combinatorics = "1.0"
DataFrames = "0.18, 0.20, 0.21, 0.22"
DensityRatioEstimation = "0.4"
Distances = "0.10"
Distributions = "0.21, 0.22, 0.23, 0.24"
LossFunctions = "0.6"
MLJModelInterface = "0.2, 0.3, 0.4"
NearestNeighbors = "0.4"
Optim = "0.18, 0.20, 0.21, 0.22, 1.0, 1.1, 1.2"
Parameters = "0.12"
RecipesBase = "0.7, 0.8, 1.0, 1.1"
ReferenceFrameRotations = "0.5"
ScientificTypes = "0.7, 0.8, 1.0"
SpecialFunctions = "0.7, 0.8, 0.9, 0.10, 1.0"
StaticArrays = "0.12, 1.0"
StatsBase = "0.32, 0.33"
Tables = "1.0"
Transducers = "0.4"
julia = "1.4"

[extras]
DecisionTree = "7806a523-6efd-50cb-b5f6-3fa6f1930dbb"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
GR = "28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71"
ImageMagick = "6218d12a-5da1-5696-b52f-db25d2ecc6d1"
MLJ = "add582a8-e3ab-11e8-2d5e-e98b27df1bc7"
MLJDecisionTreeInterface = "c6f25543-311c-4c74-83dc-3ea6d1015661"
MLJModels = "d491faf4-2d78-11e9-2867-c94bc002c0b7"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
QuartzImageIO = "dca85d43-d64c-5e67-8c65-017450d5d020"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
VisualRegressionTests = "34922c18-7c2a-561c-bac1-01e79b2c4c92"

[targets]
test = ["DelimitedFiles", "Pkg", "GR", "VisualRegressionTests", "Test", "Plots", "ImageMagick", "QuartzImageIO", "Random", "DecisionTree", "MLJ", "MLJModels", "MLJDecisionTreeInterface"]
